name: Build a SimpleX SMP and XFTP Docker image for ARM64 and AMD64

on:
  push:
    branches:
      - 'main'

jobs:
  smp-server:
    name: Build smp-server image
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v3
        with:
          repository: simplex-chat/simplexmq
          ref: stable
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/amd64,linux/arm64
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64,linux/arm64
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Log in to the Github container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUBB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
              "maxvdm/simplex-smp:5.2.1"
              "ghcr.io/maxvdmerwe/simplex-smp:5.2.1"
          shim: 2g
          build-args: |
              "APP=smp-server"
              "APP_PORT=5223"
          context: /home/runner/work/simplex/simplex/
  xftp-server:
    name: Build xftp-server image
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v3
        with:
          repository: simplex-chat/simplexmq
          ref: stable
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/amd64,linux/arm64
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64,linux/arm64
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Log in to the Github container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUBB_TOKEN }}    
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
             "maxvdm/simplex-xftp:5.2.1"
             "ghcr.io/maxvdmerwe/simplex-xftp:5.2.1"
          shim: 2g
          build-args: |
              "APP=xftp-server"
              "APP_PORT=443"
          context: /home/runner/work/simplex/simplex/
